ts = {
    "activitiesEntered":"活动参与场数",
    "activitiesWon":"胜利场数",
    "assists":"助攻数",
    "totalDeathDistance":"总死亡距离",
    "averageDeathDistance":"平均死亡距离",
    "totalKillDistance":"总击杀距离",
    "kills":"击杀数",
    "averageKillDistance":"平均击杀距离",
    "secondsPlayed":"游玩时间",
    "deaths":"死亡数",
    "averageLifespan":"平均存活时间",
    "score":"分数",
    "averageScorePerKill":"每击杀平均得分",
    "averageScorePerLife":"单条命平均得分",
    "bestSingleGameKills":"最佳单局击杀数",
    "bestSingleGameScore":"最佳单局分数",
    "opponentsDefeated":"对手击败数",
    "efficiency":"效率",
    "killsDeathsRatio":"KD",
    "killsDeathsAssists":"Kda",
    "objectivesCompleted":"完成目标数",
    "precisionKills":"精准击杀数",
    "resurrectionsPerformed":"复活他人数",
    "resurrectionsReceived":"被复活次数",
    "suicides":"自杀数",
    "weaponKillsAutoRifle":"自动步枪击杀数",
    "weaponKillsBeamRifle":"线性融合步枪击杀数",
    "weaponKillsBow":"弓箭击杀数",
    "weaponKillsFusionRifle":"聚合步枪击杀数",
    "weaponKillsHandCannon":"手炮击杀数",
    "weaponKillsTraceRifle":"追踪步枪击杀数",
    "weaponKillsMachineGun":"机枪击杀数",
    "weaponKillsPulseRifle":"脉冲步枪击杀数",
    "weaponKillsRocketLauncher":"火箭发射器击杀数",
    "weaponKillsScoutRifle":"斥候步枪击杀数",
    "weaponKillsShotgun":"霰弹枪击杀数",
    "weaponKillsSniper":"狙击枪击杀数",
    "weaponKillsSubmachinegun":"微型冲锋枪击杀数",
    "weaponKillsRelic":"圣物击杀数",
    "weaponKillsSideArm":"手枪击杀数",
    "weaponKillsSword":"刀剑击杀数",
    "weaponKillsAbility":"技能击杀数",
    "weaponKillsGrenade":"手雷击杀数",
    "weaponKillsGrenadeLauncher":"榴弹发射器击杀数",
    "weaponKillsSuper":"超能击杀数",
    "weaponKillsMelee":"近战击杀数",
    "weaponBestType":"最佳武器类型",
    "winLossRatio":"胜负比",
    "allParticipantsCount":"参与活动玩家总人数",
    "allParticipantsScore":"参与活动玩家总分数",
    "allParticipantsTimePlayed":"参与活动玩家总时长",
    "longestKillSpree":"最高连杀数",
    "longestSingleLife":"最长存活时间",
    "mostPrecisionKills":"最高单局精准击杀",
    "orbsDropped":"能量球体生成数",
    "orbsGathered":"能量球体拾取数",
    "remainingTimeAfterQuitSeconds":"提前退出活动后剩余时间",
    "teamScore":"队伍分数",
    "totalActivityDurationSeconds":"活动消耗时间",
    "combatRating":"战斗评分",
    "fastestCompletionMs":"最快完成时间",
    "longestKillDistance":"最长杀伤距离",
    "highestCharacterLevel":"最高角色等级",
    "highestLightLevel":"最高光等",
    "fireTeamActivities":"组队参与活动数",
    "activitiesCleared":"活动完成数",
    "heroicPublicEventsCompleted":"英雄公共事件完成数",
    "adventuresCompleted":"探险完成数",
    "publicEventsCompleted":"公共事件完成数",
    "assists_pga":"平均单局助攻数",
    "kills_pga":"平均单局击杀数",
    "secondsPlayed_pga":"平均单局游玩时间",
    "deaths_pga":"平均单局死亡数",
    "score_pga":"平均单局分数",
    "objectivesCompleted_pga":"平均单局完成目标数",
    "precisionKills_pga":"平均单局精准击杀数",
    "resurrectionsPerformed_pga":"平均单局复活他人数",
    "resurrectionsReceived_pga":"平均单局被复活次数",
    "suicides_pga":"平均单局自杀数",
    "weaponKillsAutoRifle_pga":"平均单局自动步枪击杀数",
    "weaponKillsBeamRifle_pga":"平均单局线性融合步枪击杀数",
    "weaponKillsBow_pga":"平均单局弓箭击杀数",
    "weaponKillsFusionRifle_pga":"平均单局聚合步枪击杀数",
    "weaponKillsHandCannon_pga":"平均单局手炮击杀数",
    "weaponKillsTraceRifle_pga":"平均单局追踪步枪击杀数",
    "weaponKillsMachineGun_pga":"平均单局机枪击杀数",
    "weaponKillsPulseRifle_pga":"平均单局脉冲步枪击杀数",
    "weaponKillsRocketLauncher_pga":"平均单局火箭发射器击杀数",
    "weaponKillsScoutRifle_pga":"平均单局斥候步枪击杀数",
    "weaponKillsShotgun_pga":"平均单局霰弹枪击杀数",
    "weaponKillsSniper_pga":"平均单局狙击枪击杀数",
    "weaponKillsSubmachinegun_pga":"平均单局微型冲锋枪击杀数",
    "weaponKillsRelic_pga":"平均单局圣物击杀数",
    "weaponKillsSideArm_pga":"平均单局手枪击杀数",
    "weaponKillsSword_pga":"平均单局刀剑击杀数",
    "weaponKillsAbility_pga":"平均单局技能击杀数",
    "weaponKillsGrenade_pga":"平均单局手雷击杀数",
    "weaponKillsGrenadeLauncher_pga":"平均单局榴弹发射器击杀数",
    "weaponKillsSuper_pga":"平均单局超能击杀数",
    "weaponKillsMelee_pga":"平均单局近战击杀数",
    "orbsDropped_pga":"平均单局能量球体生成数",
    "orbsGathered_pga":"平均单局能量球体拾取数",
    "remainingTimeAfterQuitSeconds_pga":"平均单局提前退出活动后剩余时间",
    "teamScore_pga":"平均单局队伍分数",
    "totalActivityDurationSeconds_pga":"平均单局活动消耗时间",
    "heroicPublicEventsCompleted_pga":"英雄公共事件平均完成数",
    "adventuresCompleted_pga":"探险平均完成数",
    "publicEventsCompleted_pga":"公共事件平均完成数",
    "winRatio":"胜率",
    "hoursPlayed":"游玩时间"
}

play_list_name_ts = {
    "Control":"占领",
    "Clash":"死斗",
    "Iron Banner":"铁骑",
    "Mayhem":"激战",
    "Supremacy":"霸权",
    "Survival":"生存",
    "Rumble":"混战",
    "Gambit Prime":"全盛智谋",
    "Gambit":"智谋",
    "Trials of Osiris":"TOO",
    "Elimination":"灭绝",
    "Countdown":"分秒必争",
    "Showdown":"正面对决",
    "Lockdown":"全面攻占",
    "Breakthrough":"突破防线",
}

rank_name_ts = {
    "Bronze I":"青铜I",
    "Bronze II":"青铜II",
    "Bronze III":"青铜III",
    "Silver I":"白银I",
    "Silver II":"白银II",
    "Silver III":"白银III",
    "Gold I":"黄金I",
    "Gold II":"黄金II",
    "Gold III":"黄金III",
    "Platinum I":"铂金I",
    "Platinum II":"铂金II",
    "Platinum III":"铂金III",
    "Diamond I":"钻石I",
    "Diamond II":"钻石II",
    "Diamond III":"钻石III",
    "Top 500":"世界500强",
}