playListNameEN2CHS = {
    "Control":"占领",
    "Clash":"死斗",
    "Iron Banner":"铁骑",
    "Mayhem":"激战",
    "Supremacy":"霸权",
    "Survival":"生存",
    "Rumble":"混战",
    "Gambit Prime":"全盛智谋",
    "Gambit":"智谋",
    "Trials of Osiris":"TOO",
    "Elimination":"灭绝",
    "Countdown":"分秒必争",
    "Showdown":"正面对决",
    "Lockdown":"全面攻占",
    "Breakthrough":"突破防线",
}

rankNameEN2CHS = {
    "Bronze I":"青铜I",
    "Bronze II":"青铜II",
    "Bronze III":"青铜III",
    "Silver I":"白银I",
    "Silver II":"白银II",
    "Silver III":"白银III",
    "Gold I":"黄金I",
    "Gold II":"黄金II",
    "Gold III":"黄金III",
    "Platinum I":"铂金I",
    "Platinum II":"铂金II",
    "Platinum III":"铂金III",
    "Diamond I":"钻石I",
    "Diamond II":"钻石II",
    "Diamond III":"钻石III",
    "Top 500":"世界500强",
}
